USE master;
GO
CREATE LOGIN [NT SERVICE\MSSQL$MSSQLSERVER02] FROM WINDOWS;
GO

GRANT CONNECT ON ENDPOINT::Mirroring_Endpoint_MSSQLSERVER01 TO [NT SERVICE\MSSQL$MSSQLSERVER02]; 
GO

ALTER DATABASE powerlifting__db
SET PARTNER = N'TCP://DESKTOP-OS7IBMJ:5022'; -- Sadece SÝSTEM ADI ve MSSQLSERVER02'nin PORTU
GO