--Mirroring
USE master;
GO

IF EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'NT SERVICE\MSSQL$MSSQLSERVER01')
BEGIN
    DROP LOGIN [NT SERVICE\MSSQL$MSSQLSERVER01];
    PRINT 'Mevcut [NT SERVICE\MSSQL$MSSQLSERVER01] login''i MSSQLSERVER02 üzerinden silindi.';
END
GO

CREATE LOGIN [NT SERVICE\MSSQL$MSSQLSERVER01] FROM WINDOWS;
PRINT '[NT SERVICE\MSSQL$MSSQLSERVER01] login''i MSSQLSERVER02 üzerinde oluþturuldu.';
GO

GRANT CONNECT ON ENDPOINT::Mirroring_Endpoint_MSSQLSERVER02 TO [NT SERVICE\MSSQL$MSSQLSERVER01];
PRINT '[NT SERVICE\MSSQL$MSSQLSERVER01] login''ine Mirroring_Endpoint_MSSQLSERVER02 için CONNECT izni verildi.';
GO

